apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5055
  type: {{ .Values.service.type }}
