apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.nginx.containerPort }} 
      nodePort: 30001
  type: {{ .Values.service.type }}
