apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
spec:
  selector:
    app: {{ .Values.service.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
      nodePort: 30001
  type: {{ .Values.service.type}}
