{{- with .Values.database.StatefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
spec:
  serviceName: {{ .name | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.database.spec.containers.image }}:{{ $.Values.database.spec.containers.tags }}
          volumeMounts:
            - name: gripodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: gripodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
{{- end }}
