apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.StatefulSet.name }}
spec:
  replicas: {{ .Values.database.StatefulSet.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.database.StatefulSet.name }}
  serviceName: {{ .Values.database.StatefulSet.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.StatefulSet.name }}
    spec:
      containers:
        {{- range .Values.database.StatefulSet.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 27017
        {{- end }}
