apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.StatefulSet.name}}
spec:
  selector:
    app: {{ .Values.database.StatefulSet.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port}}
      targetPort: {{ .Values.database.service.targetPort}}
  clusterIP: None
