
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.Deployment.containers.name }} 
spec:
  selector:
    app: {{ .Values.frontend.Deployment.containers.name }}  
  ports:
    - protocol: {{ .Values.frontend.service.ports.protocol }} 
      port: {{ .Values.frontend.service.ports.port }} 
      targetPort: {{ .Values.frontend.service.ports.targetPort }} 
  type: {{ .Values.frontend.service.ports.type}} 