{{- with .Values.frontend.Deployment }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .containers.name }}
  labels:
    app: {{ .containers.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .containers.name }}
  template:
    metadata:
      labels:
        app: {{ .containers.name }}
    spec:
      containers:
        - name: {{ .containers.name }}
          image: {{ .containers.image }}:{{ .containers.tags }}

{{- end }}
