apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-expose-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ingress-expose-nginx.local
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: gripo-frontend 
                port:
                  number: 3000 