replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5055
  targetPort: 5055
  name: nginx

ports: 
  port: 5055

nginx:
  containerPort: 5055
  # env:
  #   LISTEN_PORT: "5055"
  #   API_BACKEND: "5080"
  #   TERMINAL_BACKEND: "8377"
  #   FRONTEND_BACKEND: "3000"

# livenessProbe:
#   httpGet:
#     path: /
#     port: 80  # Corrected to 80
# readinessProbe:
#   httpGet:
#     path: /
#     port: 80  # Corrected to 80

# replicaCount: 1

# image:
#   pullPolicy: IfNotPresent

# service:
#   type: NodePort
#   port: 5055
#   targetPort: 5055
#   name: nginx
# ports: 
#   port: 5055
# nginx:
#   containerPort: 80
#   env:
#     LISTEN_PORT: "5055"     # Make sure LISTEN_PORT is nested under nginx.env
#     API_BACKEND: "5080"
#     TERMINAL_BACKEND: "8377"
#     FRONTEND_BACKEND: "3000"

# livenessProbe:
#   httpGet:
#     path: /
#     port: http

# readinessProbe:
#   httpGet:
#     path: /
#     port: http
