replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  port: 5055
  type: NodePort

deployment:
  containers:
    name: nginx
    image: gripo/gripo-nginx:1.0
    ports:
      - containerPort: 5055
    env:
      LISTEN_PORT: "5055"
      API_BACKEND: "http://gripo-application:5080"
      TERMINAL_BACKEND: "http://gripo-terminal:8377"
      FRONTEND_BACKEND: "http://gripo-frontend:3000"
