replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  port: 5055
  type: LoadBalancer

deployment:
  containers:
    name: nginx
    image: gripo/gripo-nginx:1.0
    ports:
      - containerPort: 5055
    env:
      LISTEN_PORT: "5055"
      API_BACKEND: "http://gripo-application:5080"
      TERMINAL_BACKEND: "http://gripo-terminal:8377"
      FRONTEND_BACKEND: "http://gripo-frontend:3000"
terminal:
  name: gripo-terminal
  containers:
    image: gripo/gripo-terminal
    tags: beta-1.0
  service:
    ports:
    - protocol: TCP
      port: 8377
      targetPort: 8377
  type: ClusterIP
redis:
  name: gripo-redis
  containers:
    image: gripo/gripo-redis
    tags: "1.0"
  service:
    ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
application:
  name: gripo-application
  containers:
    image: gripo/gripo-application
    tags: beta-1.0
    env:
      - name: GRIPO_SERVER_ADDRESS
        value: ":5080"
  service:
    ports:
      - protocol: TCP
        port: 5080
        targetPort: 5080
  type: ClusterIP
frontend:
  Deployment:
    containers:
      name: gripo-frontend
      image: gripo/gripo-frontend
      tags: beta-1.0
  service:
    ports:
      protocol: TCP 
      port: 3000
      targetPort: 3000
      type: ClusterIP
database:
  StatefulSet:
    name:  gripo-db 
  spec:
    containers:
      image: gripo/gripo-db:1.0
  service:
    targetPort: 27017
    port: 27017  
