name: Update Helm Chart Repo Index

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm package ./charts/

      - name: Create or Update Helm Repo Index
        run: |
          helm repo index ./ --url https://github.com/// --merge index.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.yaml
          git commit -m "Update Helm repo index"
          git push origin main
