{{- with .Values.application }}
  
apiVersion: v1
kind: Service
metadata:
  name: {{.name}}
spec:
  selector:
    app: {{.name}}
  ports:
    {{- range .service.ports}}
    - protocol: {{.protocol}}
      port: {{.port}}
      targetPort: {{.targetPort}}
    {{- end}}
  type: {{.type}}
{{end}}