apiVersion: apps/v1
kind: Deployment
metadata:
  name: gripo-application
  labels:
    app: gripo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gripo-application
  template:
    metadata:
      labels:
        app: gripo-application
    spec:
      containers:
        - name: gripo-application
          image: gripo/gripo-application:beta-1.0
          env:
            - name: GRIPO_SERVER_ADDRESS
              value: ":5080"
