{{- with .Values.application }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .containers.image }}:{{ .containers.tags }}
          env:
            {{- range .containers.env }}
            - name: {{ .name }} 
              value: {{ .value | quote }}  
            {{- end }}
{{- end }}
